### ISSUE TITLE
commit de68f80 drops support for Racket 6.2

### ISSUE THREAD

**Issue by greghendershott** [lexi-lambda/threading#12] opened 2017-06-12 21:34 UTC
Travis ran a "cron" job today on frog and [it failed for Racket 6.2](https://travis-ci.org/greghendershott/frog/jobs/242155143#L230-L235):

```
Downloading https://github.com/lexi-lambda/threading/tarball/dee85e8d3cffaed85eb27bed8a8c61fc1eea8395
raco pkg install: version mismatch for dependency
  for package: rackjure
  mismatch packages:
   threading (have 0.0, need 1.1)
make: *** [install] Error 1
```

It looks like this is due to your recent commit de68f80 ?

Interestingly frog [built fine for Racket 6.1 and 6.1.1](https://travis-ci.org/greghendershott/frog/builds/242155139) -- is that because you have a version exception?  It looks like 6.2 is falling between these two approaches?

---

Note that Pollen uses markdown which uses rackjure which uses threading, so, I'm kind of caught in the middle here. On April 11 I dropped support some older Rackets but @mbutterick said Pollen needs to support 6.0 so I undid that on April 12.

**Comment by lexi-lambda** [comment] 2017-06-12 21:45
Odd. I added version exceptions for 6.2 and 6.2.1 when I made that commit, so I’m trying to understand why the Travis build fails on 6.2. I’ll try and investigate.

**Comment by lexi-lambda** [comment] 2017-06-12 21:51
Should be fixed now if you re-run the job; I had a misconfigured version exception. Thanks for catching this, and it shows that continuous integration is working as intended. :)

**Closed as completed by lexi-lambda** 2017-06-12 21:51 UTC

**Comment by greghendershott** [comment] 2017-06-13 14:47
Thanks!!

It's only within the last couple months that I enabled a Travis CI "cron" job (build periodically even if the repo itself hasn't changed) for Frog. Although the Racket package server does some equivalent of this it's only for the most-recent Racket version.
